### ISSUE TITLE
Evaluating 'ImageColorsModule.getColors' error

### ISSUE THREAD

**Issue by CharliBregnballe** [osamaqarem/react-native-image-colors#14]
Hi,
I am getting the following error when trying to fetch colors from an image:
`[Unhandled promise rejection: TypeError: null is not an object (evaluating 'ImageColorsModule.getColors')]
- node_modules/react-native-image-colors/index.js:7:26 in ImageColors.getColors`

The object (or the url of the image) is not null.

Looks like an awesome library and I really hope I can make it work :)

**Comment by osamaqarem** [comment]
Thanks!
If you could post your code, that'd help me troubleshoot it.

**Comment by CharliBregnballe** [comment]
I actually just used the code from your example.
But I am running Expo, which might cause the error?

**Comment by osamaqarem** [comment]
Sorry, this library is using native code therefore it's not compatible with expo managed projects. You have to eject to install it.

**Comment by CharliBregnballe** [comment]
Alrighty!  Thank you for your answer :)

**Comment by Alpovka** [comment]
> Sorry, this library is using native code therefore it's not compatible with expo managed projects. You have to eject to install it.

Then why did you said that the example of this project has been made in expo ?? You said it is working in expo in description. But you are now saying it won't work in expo project. Please update your repo desc otherwise people will get confuse and lose hours with finding solution like I'm.

Thank you

**Comment by osamaqarem** [comment]
> > Sorry, this library is using native code therefore it's not compatible with expo managed projects. You have to eject to install it.
> 
> 
> 
> Then why did you said that the example of this project has been made in expo ?? You said it is working in expo in description. But you are now saying it won't work in expo project. Please update your repo desc otherwise people will get confuse and lose hours with finding solution like I'm.
> 
> 
> 
> Thank you

Sorry, what do you mean by "now"? My comment you're quoting is from 2 years ago. The library does support expo today and the docs are correct to say so. In fact the example app in the repo is an expo app.

**Comment by Alpovka** [comment]
> > > Sorry, this library is using native code therefore it's not compatible with expo managed projects. You have to eject to install it.
> > 
> > 
> > Then why did you said that the example of this project has been made in expo ?? You said it is working in expo in description. But you are now saying it won't work in expo project. Please update your repo desc otherwise people will get confuse and lose hours with finding solution like I'm.
> > Thank you
> 
> Sorry, what do you mean by "now"? My comment you're quoting is from 2 years ago. The library does support expo today and the docs are correct to say so. In fact the example app in the repo is an expo app.

Yeah, I mean now like now, right now. And it is not working. :) Hope I'm wrong but still taking same error as said in the issue.

**Comment by osamaqarem** [comment]
> > > > Sorry, this library is using native code therefore it's not compatible with expo managed projects. You have to eject to install it.
> 
> > > 
> 
> > > 
> 
> > > Then why did you said that the example of this project has been made in expo ?? You said it is working in expo in description. But you are now saying it won't work in expo project. Please update your repo desc otherwise people will get confuse and lose hours with finding solution like I'm.
> 
> > > Thank you
> 
> > 
> 
> > Sorry, what do you mean by "now"? My comment you're quoting is from 2 years ago. The library does support expo today and the docs are correct to say so. In fact the example app in the repo is an expo app.
> 
> 
> 
> Yeah, I mean now like now, right now. And it is not working. :) Hope I'm wrong but still taking same error as said in the issue.

If you followed the steps in the README and still could not get it to work, feel free to submit a new issue about it. A repo with a minimum reproducible example would be the fastest way to understand the problem you're facing.

**Comment by Alpovka** [comment]
> > > > > Sorry, this library is using native code therefore it's not compatible with expo managed projects. You have to eject to install it.
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > Then why did you said that the example of this project has been made in expo ?? You said it is working in expo in description. But you are now saying it won't work in expo project. Please update your repo desc otherwise people will get confuse and lose hours with finding solution like I'm.
> > 
> > 
> > > > Thank you
> > 
> > 
> > > 
> > 
> > 
> > > Sorry, what do you mean by "now"? My comment you're quoting is from 2 years ago. The library does support expo today and the docs are correct to say so. In fact the example app in the repo is an expo app.
> > 
> > 
> > Yeah, I mean now like now, right now. And it is not working. :) Hope I'm wrong but still taking same error as said in the issue.
> 
> If you followed the steps in the README and still could not get it to work, feel free to submit a new issue about it. A repo with a minimum reproducible example would be the fastest way to understand the problem you're facing.

Okey, I will try more if not works. Will open the issue. Thanks.

**Comment by Pranavjain23** [comment]
Possible Unhandled Promise Rejection (id: 8):
TypeError: null is not an object (evaluating '_module.RNImageColors.getColors')

Can someone help me with this issue

**Comment by aymeric75** [comment]
Hello,

Thank you for this wonderful library.

In order to make it compatible with Expo, could you please confirm that this sequence of steps is in the right order ?


- npx create-expo-app ExpoProject

- cd ExpoProject

- expo prebuild

- npm install react-native-image-colors

- npm start

Thank you

**Comment by osamaqarem** [comment]
hey @aymeric75 - I can see a mistake in your steps. the correct steps are:

```
npx create-expo-app ExpoProject;

cd ExpoProject;

npm install react-native-image-colors;

expo prebuild;

# to build for iOS or Android (first time after installing a library with native code only)
expo run:ios
expo run:android
```

unless you already did, make sure to check the README in the future. if u still need help after that - it would be nice to create a new question in [discussions](https://github.com/osamaqarem/react-native-image-colors/discussions) or a new issue if you think its a problem in the library. this is cool since we avoid bothering the author of this github issue 🌈

**Comment by aymeric75** [comment]
I have done all the steps still this issue of null object with an Expo managed app...

**Comment by osamaqarem** [comment]
I just tested the above steps and it is working on my end.
At this point the quickest way I can help is if you can take the time to create a new github issue along with a repository created with `create-expo-app` where I can reproduce the error you are seeing.

**Comment by aymeric75** [comment]
Hello @osamaqarem thanks for you help, I am going to do this.

**Comment by joeydotdev** [comment]
Just ran through the install steps listed for expo and can also confirm it's working for me.
