### ISSUE TITLE
Color edit

### ISSUE THREAD

**Issue by Merrick17** [osamaqarem/react-native-image-colors#20]
Awesome Package , 
But is there any way to edit the colors ??

**Comment by osamaqarem** [comment]
Hi, thanks. 
Can you clarify what you mean by editing colors?

**Comment by Merrick17** [comment]
I mean to change the color for example the red one force it to become blue ( adding a filter or something )

**Comment by osamaqarem** [comment]
This library is only about getting the true colors from the image so there is no way to do that.
I think you should look for a color filter package and then maybe apply the output from this library as the input to the filters from the other library.
