### ISSUE TITLE
Error: ImageColors: Illegal character in opaque part at index 98

### ISSUE THREAD

**Issue by km147** [osamaqarem/react-native-image-colors#40]
I'm using react-native-android-installed-apps to receive base64 data for icons of app installed on the device and trying to get the colors for each one use `getColors()`. However this throws the following error:

`Error: ImageColors: Illegal character in opaque part at index 98:`

I manually had to append `data:image/png;base64,` to the beginning of the base64 data returned by react-native-android-installed-apps and wondering if that is part of the problem?

Here's what I'm trying:

```
const img = `data:image/png;base64,${this.props.item.icon.trim()}`;
const result = await ImageColors.getColors(img, {
        fallback: '#cccccc',
        cache: true,
        key: this.props.item.packageName,
 });
```

Getting the same result on emulators running Android 9 to 11.

I can provide an example of the base64 data I'm using if needed?

**Comment by mtahir08** [comment]
any update?

**Comment by osamaqarem** [comment]
Sorry I'm currently in the process of relocating to another country so I will be too occupied to check this for a while

**Comment by osamaqarem** [comment]
Hello again, can you please provide an example of the failing base64 string?
