### ISSUE TITLE
Android crash

### ISSUE THREAD

**Issue by oferRounds** [osamaqarem/react-native-image-colors#41]
![image](https://user-images.githubusercontent.com/1477963/142830244-120d657d-ae46-4a8c-9c49-5c08618cc2c4.png)

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | 1.3.0   |
| react-native-native | 0.64.2   |

See on the image more details on the device

Happens when calling  `ImageColors.getColors(url, { cache: true })`

**Comment by osamaqarem** [comment]
Sorry it's crashing for you. However I don't think we can solve this without more information about the scenario. 
A minimum reproducible example would be very helpful.

**Comment by osamaqarem** [comment]
I'm going to close this issue for now but please feel free to reopen it if you can share reproducability steps

**Comment by codeyogi911** [comment]
I am also having the same issue.
