### ISSUE TITLE
how to use on web

### ISSUE THREAD

**Issue by ithustle** [osamaqarem/react-native-image-colors#42]
I've installed on my project reactjs and typescript but it doesn't work. 

```
./node_modules/node-libs-browser/node_modules/url/url.js
Error: ENOENT: no such file or directory, open '/Users/.../node_modules/node-libs-browser/node_modules/url/url.js'
```

**Comment by osamaqarem** [comment]
Your project must be using [react-native-web](https://github.com/necolas/react-native-web)

I recommend creating an expo project to skip all the necessary configuration: 

- https://docs.expo.dev/workflow/web/
- https://docs.expo.dev/get-started/create-a-new-app/

**Comment by osamaqarem** [comment]
To be clear when **react-native**-x library supports web, it almost always means through react-native-web.

If you have a pure React web project and no interest in react-native, there are lots of web only libraries for getting colors from images. e.g. node-vibrant
