### ISSUE TITLE
Expo "Possible Unhandled Promise Rejection: TypeError: Cannot read property 'getColors' of undefined" issue

### ISSUE THREAD

**Issue by Alpovka** [osamaqarem/react-native-image-colors#56]
I'm trying to paint the background of my card element according to image on the card, using this repo. These individual cards are rendered in a horizontal view by mapping.

The code of the card component is given below. I want to get the desired color of asset.imgUrl . And paint the background color of card to that color. But when I'm trying to get the color, getColor property is given me an warning

> Possible Unhandled Promise Rejection (id: <some-id>): TypeError: Cannot read property 'getColors' of undefined

I've check the URLs and coming data. But everything was looking fine. Why getColor is not working and giving me an unhandled promise error ?

```
import {
  Text,
  StyleSheet,
  View,
  Image,
  Pressable,
  ActivityIndicator,
} from "react-native";
import { textStylesEQ } from "../constants/textStyles";
import { useNavigation } from "@react-navigation/native";
import ImageColors from "react-native-image-colors";
import { useEffect, useState } from "react";

const initialState = {
  colorOne: { value: "", name: "" },
  colorTwo: { value: "", name: "" },
  rawResult: "",
};

const AssetCard = ({ asset }) => {
  const [colors, setColors] = useState(initialState);
  const [loading, setLoading] = useState(true);

  const navigation = useNavigation();

  const navigateToAssetDetails = (asset) => {
    navigation.navigate("AssetDetails", { asset });
  };

  useEffect(() => {
    const fetchColors = async () => {
      const result = await ImageColors.getColors(asset.imageUrl, {
        fallback: "blue",
        quality: "high",
        pixelSpacing: 5,
        cache: true,
      });

      switch (result.platform) {
        case "android":
          setColors({
            colorOne: { value: result.lightVibrant, name: "lightVibrant" },
            colorTwo: { value: result.average, name: "average" },
            rawResult: JSON.stringify(result),
          });
          break;
        case "ios":
          setColors({
            colorOne: { value: result.detail, name: "detail" },
            colorTwo: { value: result.background, name: "background" },
            rawResult: JSON.stringify(result),
          });
          break;
        default:
          throw new Error("Unexpected platform");
      }

      console.log(colors);

      setLoading(false);
    };

    fetchColors();
  }, []);

  if (loading) {
    return <ActivityIndicator />;
  }

  return (
    <>
      <Pressable key={asset._id} onPress={() => navigateToAssetDetails(asset)}>
        <View style={styles.assetContainer}>
          <View
            style={{
              width: "100%",
              flexDirection: "row",
              alignItems: "center",
              justifyContent: "space-between",
            }}
          >
            <Image
              style={{ height: 40, width: 40, borderRadius: 50 }}
              source={{ uri: asset.imageUrl }}
              resizeMode="contain"
            />
            <Some stuff need to be secret />
          </View>
        </View>
      </Pressable>
    </>
  );
};

const styles = StyleSheet.create({
  assetContainer: {
    alignItems: "flex-start",
    justifyContent: "space-between",
    backgroundColor: "blue",
    padding: 10,
    marginRight: 20,
    borderRadius: 20,
    width: 135,
    height: 170,
  },
  assetImage: {
    width: "100%",
  },
});

export default AssetCard;
```

**Comment by osamaqarem** [comment]
Hello. This error is likely due to a problem in the integration with the package's native code. Can you provide the steps you've taken to integrate this library in your project?

**Comment by Alpovka** [comment]
1. yarn add react-native-image-colors
2. expo prebuild
3. start command for the project

(I got the expo-dev-client)

**Comment by osamaqarem** [comment]
> 1. yarn add react-native-image-colors
> 2. expo prebuild
> 3. start command for the project

What command did you run in step 3? It should be `expo run:ios` or `expo run:android`. Is that correct?

**Comment by Alpovka** [comment]
Yes

**Comment by osamaqarem** [comment]
Hmm.. the code and steps seem correct to me – I'm not sure what is the problem. Could you share a repo with the same issue? I could take a look there.

**Comment by Alpovka** [comment]
> Hmm.. the code and steps seem correct to me – I'm not sure what is the problem. Could you share a repo with the same issue? I could take a look there.

I mean I'm trying to integrate to my company's codebase so it would inappropriate for me to share. Is it possible for you to make a call or something to tackle this? After solving this we can write down in here for the other people.

**Comment by Alpovka** [comment]
Anyways, I will not do this color detection thing on the frontend. Making this on database would be more nice approach. So I will close this issue. Thanks for help.
