### ISSUE TITLE
This is not working in Apple tv .

### ISSUE THREAD

**Issue by rsys2022** [osamaqarem/react-native-image-colors#59]
# **Bug**

Getting this error in Apple tv simulator
TypeError: null is not an object (evaluating '_$$_REQUIRE(_dependencyMap[4], "./module").RNImageColors.getColors')

**## Environment info**
**Apple tv-     Not working**
iOS mobile-  Working 
Android mobile-  Working
Android mobile- Working
**Web - Not working**

**Library**
 "react-native-image-colors": "^1.5.1",
 "react": "17.0.2",
 "react-native": "npm:react-native-tvos@0.66.3-0",

## Reproducible sample code
**//get primary color of the given image url
export const imgBGPrimaryColor=async(url)=>{
  try {
    console.log('--url------',url)
    const result = await ImageColors.getColors(url, {
      fallback: '#4d5152',
      cache: false,
      key: url,
    })
    return result;
  } catch (e) {
    throw e;
  }
}**

## Please provide the support, Please help i am stuck here

**Comment by Leena-Sharma-rsys** [comment]
same here

**Comment by osamaqarem** [comment]
hey, this package does not support Apple TV. If you check the README, you will find that compatible platforms are Android, iOS and Web.

**Comment by osamaqarem** [comment]
I imagine it cant be that hard to add support for it as its likely very identical to the iOS implementation.
If you would like to submit a PR for that I wouldn't mind reviewing it but I have no experience with Apple TV development.

**Comment by rsys2022** [comment]
actually i am getting null from native module in case of apple tv and on other platform working properly

**Comment by osamaqarem** [comment]
sorry i'm not sure I understand clearly. if you are getting null errors on Apple TV, it is expected as Apple TV is not supported.

**Comment by rsys2022** [comment]
can you help me for adding support for apple tv

**Comment by rsys2022** [comment]
where we can add support for apple tv in this library, can you suggest ?

**Comment by osamaqarem** [comment]
Apologies, I have no experience in React Native for Apple TV and can't help you technically.
If you figure it out, I don't mind reviewing and merging a PR to this package and making you the maintainer for it 👍
