### ISSUE TITLE
Need to update kotlin-gradle-plugin to 1.6.20 as kotlin-android-extensions needs gradle plugin version >= 1.6.20 

### ISSUE THREAD

**Issue by nateshmbhat** [osamaqarem/react-native-image-colors#62]
We are using react native 0.71.1 and this uses 

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: ./gradlew app:installProdDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':react-native-image-colors' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.0

**Comment by osamaqarem** [comment]
Please try declaring the required kotlin version in your project as in this comment, and let me know if the issue persists.

https://github.com/osamaqarem/react-native-image-colors/pull/60#issuecomment-1417012281
