### ISSUE TITLE
Error when building for Android with Expo SDK 49 and React Native 0.72.1

### ISSUE THREAD

**Issue by ale-mazz** [osamaqarem/react-native-image-colors#75]
# Bug

After upgrading to Expo SDK 49, when building a new version for Android, an error pops up.

`Could not set unknown property 'classifier' for task ':react-native-image-colors:androidSourcesJar' of type org.gradle.api.tasks.bundling.Jar.`

## Environment info

React native: 0.72.1
Expo: 49.0.0

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | 2.2.0   |

## Steps To Reproduce

1. Upgrade to Expo SDK 49 and React Native 0.72.1
2. Build a version for Android with `yarn android`

![image](https://github.com/osamaqarem/react-native-image-colors/assets/15525839/66e34dda-7967-44f6-be81-6158ee318334)

**Comment by KrzysztofMoch** [comment]
Hey @ale-mazz, this error is solved by #76.
Release should be on days

**Comment by ale-mazz** [comment]
Thank you for promptly solving the problem @KrzysztofMoch!
