### ISSUE TITLE
Pod install not working after installing react-native-image-colors

### ISSUE THREAD

**Issue by LandyCuadra** [osamaqarem/react-native-image-colors#79]
# Bug

Hi guys, I tried adding this library to a project I am working on, but after installing tha package, when I try to run `npx pod-install` I get this error

I already install the expo modules since I saw it was required, and if I unninstall the `react-native-image-colors` pod install works that's why I guess the issue can be around here, or something conflicting with library but I don't get any insight from the error message
![image](https://github.com/osamaqarem/react-native-image-colors/assets/33645795/71aabdf6-0b63-49dd-9d78-d1f1c47dd75a)

Also if I run the pod install command with verbose flag, I get somewhat more information but nothing I consider really useful, since the android manifest do not anything but `<manifest>` tag

thanks beforehand

![image](https://github.com/osamaqarem/react-native-image-colors/assets/33645795/0ef629d7-ebfb-4bfe-b9d6-587bc9b8bebb)

## Environment info

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | ^2.3.0   |

**Comment by osamaqarem** [comment]
It's hard to know what's happening without the ability to reproduce the problem - could you share a repo with a fresh project reproducing the issue?

**Comment by LandyCuadra** [comment]
@osamaqarem yeah you are right, I did create a repo where this is happening you can find it here https://github.com/LandyCuadra/peliculasApp

**Comment by osamaqarem** [comment]
>  could you share a repo with a **fresh** project reproducing the issue?

Thanks for the link - but I just noticed this project isn't fresh. Would you be able to reproduce it on a fresh React Native project?
