### ISSUE TITLE
Cannot find native module 'ImageColors'

### ISSUE THREAD

**Issue by nayanLr** [osamaqarem/react-native-image-colors#80]
# Bug

**NOT WORKING IN REACT_NATIVE_CLI**

## Environment info

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | ^2.3.0  |

## Steps To Reproduce

1. npm install react-native-image-colors
2. npx react-native start then press a for android

Describe what you expected to happen:

1. When app is open and direct show this error : cannot find native module 'ImageColors'

## Reproducible sample code

**State**

  const [backgroundColors, setBackgroundColors] = useState<any>({});

**Fatching Image Color Function**

  const fetchImageColor = async (imageUrl: any, index: any) => {

    try {
      const colors: any = await getColors(imageUrl, {
        fallback: '#228B22',
        cache: true,
        key: imageUrl,
      });
      setBackgroundColors((prevColors: any) => ({
        ...prevColors,
        [index]: colors.dominant || '#228B22',
      }));
    } catch (error) {
      console.error('Error fetching image colors:', error);
    }

  };

**Render Flatlist Item**

  const _renderItem = ({item}: any) => {

    const bgColor = backgroundColors[item?.id] || 'coolGray.200';
    if (!backgroundColors[item?.id]) {
      fetchImageColor(item?.thumbnail || item?.images[0], item?.id);
    }
    return (
      <VStack
        bg={bgColor}
        h={60}
        rounded={'md'}
        marginX={2}
        marginY={2}
        style={{
          shadowColor: '#000',
          shadowOffset: {
            width: 0,
            height: 2,
          },
          shadowOpacity: 0.25,
          shadowRadius: 3.84,
          elevation: 5,
        }}>
        {/* Image Container */}
        <Image
          size={60}
          alt={item?.title}
          borderRadius={100}
          mx={2}
          source={{
            uri: item?.thumbnail,
            cache: 'force-cache',
          }}
          fallbackSource={{
            uri: item?.images[0],
          }}
        />
      </VStack>
    );
  };

**FlatList**

<FlatList
        data={products}
        keyExtractor={(item: any, index: any) => index}
        ListEmptyComponent={_listEmptyComponent}
        renderItem={_renderItem}
      />

![Screenshot_1701674120](https://github.com/osamaqarem/react-native-image-colors/assets/118335401/121b07c7-3665-466c-ab28-b5598c6116fb)

**Comment by osamaqarem** [comment]
hey, have you configured Expo Modules?

![image](https://github.com/osamaqarem/react-native-image-colors/assets/24393922/6080bd27-c550-481f-92f4-e05d8e557cb7)

**Comment by nayanLr** [comment]
> hey, have you configured Expo Modules?
> 
> ![image](https://private-user-images.githubusercontent.com/24393922/287782376-6080bd27-c550-481f-92f4-e05d8e557cb7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NTIyOTQsIm5iZiI6MTcwMTc1MTk5NCwicGF0aCI6Ii8yNDM5MzkyMi8yODc3ODIzNzYtNjA4MGJkMjctYzU1MC00ODFmLTkyZjQtZTA1ZDhlNTU3Y2I3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA0NTMxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQxMjMxNDVhMThmMWUwZDkwNTI5YTVjMDJiNjQxMTExMmQxZTk0NzU3NDcxNzI0MmUwNmYwNWUxNjM4OTFkZTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SCVrXwY2ucE5cBrLhiMuOF_LK6RLdft31c8gTZ1Vznk)


Yes, I have integrated Expo configuration and required steps.
But in Expo app I was getting the above error sometime, and sometime it was working.

**Comment by osamaqarem** [comment]
Are you able to reproduce this on a fresh React Native CLI app?

**Comment by nayanLr** [comment]
> Are you able to reproduce this on a fresh React Native CLI app?

Yes!, I have been creating fresh react-native-cli project but it's not working on that.
Could you please share list of commands to configure library in react-native-cli.
my project CLI version is 0.72.7

**Comment by osamaqarem** [comment]
The commands should be as per the README. If you can share a fresh react native cli project with the issue I could take a look

**Comment by nayanLr** [comment]
> The commands should be as per the README. If you can share a fresh react native cli project with the issue I could take a look

**Comment by khorark** [comment]
I have same problem on my project init from `react-native-cli ` and RN 0.73+

**Comment by khorark** [comment]
You have a great library but I think that install **_Expo modules_** it's overhead for more projects (if that were init by `react-native-cli`)

I wrote simple lib for get main color by Android/iOS. If somebody need, you can read about it [here](https://github.com/khorark/react-native-image-dominant-color)

**Comment by nayanLr** [comment]
> You have a great library but I think that install **_Expo modules_** it's overhead for more projects (if that were init by `react-native-cli`)
> 
> I wrote simple lib for get main color by Android/iOS. If somebody need, you can read about it [here](https://github.com/khorark/react-native-image-dominant-color)

I will use your library
Thanks.

**Comment by nayanLr** [comment]
[https://github.com/khorark/react-native-image-dominant-color](url)

@khorark I used this library,
It's really cool and working fine.
Thanks.

**Comment by khorark** [comment]
@nayanLr great! If you will find some problems, please let me know

**Comment by kesha-antonov** [comment]
Same issue with RN 0.76.5

**Comment by ShameerMohammed15** [comment]
Cannot find native module 'ImageColors' having same issue
