### ISSUE TITLE
[Android] build failed

### ISSUE THREAD

**Issue by FightFarewellFearless** [osamaqarem/react-native-image-colors#84]
# Bug

build failed on react-native 0.73, using openjdk 17

Here is the error message:
```
'compileDebugJavaWithJavac' task (current target is 17) and 'compileDebugKotlin' task (current target is 11) jvm target compatibility should be set to the same Java version. Consider using JVM toolchain: https://kotl.in/gradle/jvm/toolchain
```

## Environment info

| Library                   | Version |
| ------------------------- | ------- |
| react-native-image-colors | 2.3.0   |

## Steps To Reproduce

1. Install this library and setup the expo modules
2. run `npm run android`

Describe what you expected to happen:

1.build success with no error

**Comment by osamaqarem** [comment]
Fixed by https://github.com/osamaqarem/react-native-image-colors/pull/85
Please try version 2.4.0 and re-open the issue if problem persists.
