### ISSUE TITLE
[iOS] Replace iOS underlying implementation

### ISSUE THREAD

**Issue by krisgerhard** [osamaqarem/react-native-image-colors#87]
https://github.com/jathu/UIImageColors is archived and quite outdated.
Consider a popular fork: https://github.com/FelixHerrmann/UIImageColors

**Comment by osamaqarem** [comment]
Thanks! New library looks cool, but I'll wait for it to have more traction (it's currently at 37 stars) especially since the entire library was re-written. There are no issues in consuming the unmaintained version of the library at the moment but I'll keep an eye out 👍
