### ISSUE TITLE
[Expo 51] Build failed on android

### ISSUE THREAD

**Issue by FightFarewellFearless** [osamaqarem/react-native-image-colors#89]
# Bug

```
* Where:
Script '/home/***/Documents/project/****/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 43

* What went wrong:
A problem occurred evaluating project ':react-native-image-colors'.
> Failed to apply plugin 'kotlin-android'.
   > Extension of type 'JavaPluginExtension' does not exist. Currently registered extension types: [ExtraPropertiesExtension, VersionCatalogsExtension, KotlinAndroidProjectExtension, KotlinTestsRegistry]
```

## Environment info

| Library                   | Version |
| ------------------------- | ------- |
| react-native | 0.74.0-rc.8 |
| expo | 51.0.0-preview.0 |
| react-native-image-colors | 2.4.0   |

## Steps To Reproduce

1. Running in bare react-native project
2. `npm i expo@next`

Describe what you expected to happen:

1. Build successfully
2.

**Comment by osamaqarem** [comment]
I just re-tested the library using React Native 74/Expo 51. The reproduction steps given seem incorrect. You also have to run `npx expo prebuild` as specified in the [readme](https://github.com/osamaqarem/react-native-image-colors?tab=readme-ov-file#expo).
