### ISSUE TITLE
Expo 50 Build failed on android

### ISSUE THREAD

**Issue by WilliamWatcher** [osamaqarem/react-native-image-colors#92]
# Bug

When building with expo/eas (eas build --platform android), I get the following error. Could it be a conflict with one of my other libraries than Expo 50 and React Native 0.73.6?

```
* Where:
Script '/home/expo/workingdir/build/node_modules/expo-modules-core/android/ExpoModulesCorePlugin.gradle' line: 40
* What went wrong:
A problem occurred evaluating project ':react-native-image-colors'.
>
Failed to apply plugin class 'KotlinExpoModulesCorePlugin'.
   >
Could not find method android() for arguments [KotlinExpoModulesCorePlugin$_apply_closure4@4e775278] on project ':react-native-image-colors' of type org.gradle.api.Project.
```

## Environment info

| Library                   | Version |
| ------------------------- | ------- |
| library | version |
| ------- | ------- |
| react-native-image-colors | 2.4.0 |
| expo | ^50.0.14 |
| react-native | 0.73.6 |
| @expo-google-fonts/abhaya-libre | ^0.2.3 |
| @expo-google-fonts/adamina | ^0.2.3 |
| @expo-google-fonts/eb-garamond | ^0.2.3 |
| @expo-google-fonts/inter | ^0.2.3 |
| @jridgewell/gen-mapping | ^0.3.5 |
| @react-native-async-storage/async-storage | 1.21.0 |
| @react-native-community/netinfo | 11.1.0 |
| @react-native-firebase/analytics | ^19.1.0 |
| @react-native-firebase/app | ^19.3.0 |
| @react-native-firebase/firestore | ^19.3.0 |
| @react-native-picker/picker | 2.6.1 |
| @react-navigation/bottom-tabs | ^6.5.11 |
| @react-navigation/material-top-tabs | ^6.6.5 |
| @react-navigation/native | ^6.0.10 |
| @react-navigation/stack | ^6.2.1 |
| @reduxjs/toolkit | ^1.9.7 |
| @stream-io/flat-list-mvcp | ^0.10.3 |
| ajv | ^8.17.1 |
| axios | ^1.6.7 |
| crypto-js | ^4.2.0 |
| date-fns | ^3.3.1 |
| dotenv | ^16.4.5 |
| event-register | ^1.0.6 |
| expo-asset | ~9.0.2 |
| expo-blur | ~12.9.2 |
| expo-build-properties | ~0.11.1 |
| expo-checkbox | ~2.7.0 |
| expo-constants | ~15.4.6 |
| expo-dev-client | ~3.3.12 |
| expo-device | ~5.9.4 |
| expo-file-system | ~16.0.9 |
| expo-font | ~11.10.3 |
| expo-google-fonts | ^0.0.0 |
| expo-haptics | ~12.8.1 |
| expo-image-manipulator | ~11.8.0 |
| expo-image-picker | ~14.7.1 |
| expo-linear-gradient | ~12.7.2 |
| expo-media-library | ~15.9.2 |
| expo-notifications | ~0.27.8 |
| expo-secure-store | ~12.8.1 |
| expo-splash-screen | ~0.26.5 |
| expo-status-bar | ~1.11.1 |
| expo-system-ui | ~2.9.4 |
| firebase | ^10.5.2 |
| firebase-admin | ^12.0.0 |
| glob | ^10.4.2 |
| install | ^0.13.0 |
| lodash | ^4.17.21 |
| npm | ^10.5.2 |
| openai | ^4.28.4 |
| react | 18.2.0 |
| react-dom | 18.2.0 |
| react-native-date-picker | ^5.0.7 |
| react-native-dropdown-picker | ^5.4.6 |
| react-native-event-listeners | ^1.0.7 |
| react-native-fast-image | ^8.6.3 |
| react-native-gesture-handler | ~2.14.0 |
| react-native-image-picker | ^7.1.2 |
| react-native-image-resizer | ^1.4.5 |
| react-native-ionicons | ^4.6.5 |
| react-native-pager-view | 6.2.3 |
| react-native-pell-rich-editor | ^1.9.0 |
| react-native-progress | ^5.0.1 |
| react-native-reanimated | ~3.6.2 |
| react-native-render-html | ^6.3.4 |
| react-native-safe-area-context | ^4.2.5 |
| react-native-screens | ^3.13.1 |
| react-native-svg | ^15.3.0 |
| react-native-tab-view | ^3.5.2 |
| react-native-vector-icons | ^10.0.1 |
| react-native-view-shot | 3.8.0 |
| react-native-webview | 13.6.4 |
| react-redux | ^8.1.3 |
| reanimated-color-picker | ^3.0.4 |
| redux | ^4.2.1 |
| redux-thunk | ^2.4.2 |
| reselect | ^5.1.1 |
| rimraf | ^5.0.7 |
| stream-chat-expo | ^5.32.1 |
| use-debounce | ^10.0.3 |

## Steps To Reproduce

1. `npx expo prebuild`
2. `eas build --platform android`

Describe what you expected to happen:

1. Successfull build

**Comment by brleinad** [comment]
We have the same issue.
No solution yet sorry :( 

Could this be more of an expo issue?

**Comment by admbtlr** [comment]
I'm having this problem too, but I'm not using EAS. I'm on Expo@50, trying to build with `yarn expo run:android`. I get essentially the same error as the OP:

```
A problem occurred evaluating project ':react-native-image-colors'.
> Failed to apply plugin class 'KotlinExpoModulesCorePlugin'.
   > Could not find method android() for arguments [KotlinExpoModulesCorePlugin$_apply_closure4@2968253f] on project ':react-native-image-colors' of type org.gradle.api.Project.
```

**Comment by osamaqarem** [comment]
@admbtlr could you confirm the issue with the example app in this repo? thanks!

**Comment by admbtlr** [comment]
@osamaqarem The example app works. The example is on Expo 51, while my app is still on 50, and the only reference to a similar error that I can find anywhere online seems to indicate that upgrading to 51 fixed it:

https://github.com/expo/config-plugins/issues/249

So I guess it's time to upgrade

**Comment by osamaqarem** [comment]
I see. So the issue may be exclusive to Expo 50. That's unfortunate...

**Comment by Teeticode** [comment]
for those facing this issue on sdk 50
I changed my expo version to "expo": "50.0.19"
and it is now working
