### ISSUE TITLE
[Android] Build Failed

### ISSUE THREAD

**Issue by AntBPV** [osamaqarem/react-native-image-colors#94]
# Bug

After using npx expo install react-native-image-colors, and even after using npm react-native-image-colors@latest i get the following error:
> Task :react-native-image-colors:compileDebugKotlin FAILED
Kotlin does not yet support 23 JDK target, falling back to Kotlin JVM_21 JVM target

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-image-colors:compileDebugKotlin'.
> Inconsistent JVM-target compatibility detected for tasks 'compileDebugJavaWithJavac' (17) and 'compileDebugKotlin' (21).

## Environment info

Using Expo 51

| Library                             | Version     |
|-------------------------------------|-------------|
| "@typescript-eslint/eslint-plugin": | "^8.10.0",  |
| "@typescript-eslint/parser":        | "^8.10.0",  |
| "eslint":                           | "^9.12.0",  |
| "eslint-plugin-react":              | "^7.37.1",  |
| "eslint-plugin-react-hooks":        | "^5.0.0",   |
| "expo":                             | "~51.0.28", |
| "expo-blur":                        | "~13.0.2",  |
| "expo-constants":                   | "~16.0.2",  |
| "expo-dev-client":                  | "~4.0.28",  |
| "expo-linear-gradient":             | "~13.0.2",  |
| "expo-linking":                     | "~6.3.1",   |
| "expo-router":                      | "~3.5.23",  |
| "expo-status-bar":                  | "~1.12.1",  |
| "expo-system-ui":                   | "~3.0.7",   |
| "react":                            | "18.2.0",   |
| "react-dom":                        | "18.2.0",   |
| "react-native":                     | "0.74.5",   |
| "react-native-awesome-slider":      | "^2.5.3",   |
| "react-native-fast-image":          | "^8.6.3",   |
| "react-native-gesture-handler":     | "~2.16.1",  |
| "react-native-image-colors":        | "^2.4.0",   |
| "react-native-loader-kit":          | "^2.0.8",   |
| "react-native-reanimated":          | "~3.10.1",  |
| "react-native-safe-area-context":   | "4.10.5",   |
| "react-native-screens":             | "3.31.1",   |
| "react-native-track-player":        | "^4.1.1",   |
| "react-native-web":                 | "~0.19.10", |
| "ts-pattern":                       | "^5.5.0"    |

## Steps To Reproduce

1. `npx expo install react-native-image-colors`
2. `npx expo prebuild`
3. `npx expo run`

Describe what you expected to happen:

1. App succesfully builds

**Comment by AntBPV** [comment]
Tried multiple things with AI of changing things on the android folder and more with some build.gradle files, didn't work as well

**Comment by osamaqarem** [comment]
Hey, the example app in this repo is also Expo 51 and works. 

I'm going to assume this issue is specific to your project. If you're able to reproduce it on a fresh expo project, please reopen the issue 👍
